/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>

#include "common.h"
#include "CircularBuffer.h"

#undef errno
extern int errno;

#ifndef OS_USE_SEMIHOSTING

#define STDIN_FILENO  0
#define STDOUT_FILENO 1
#define STDERR_FILENO 2

#endif

/* Variables */
extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void) __attribute__((weak));


char *__env[1] = { 0 };
char **environ = __env;


/* Functions */
void initialise_monitor_handles()
{
}

int _getpid(void)
{
	return 1;
}

int _kill(int pid, int sig)
{
	errno = EINVAL;
	return -1;
}

void _exit (int status)
{
	_kill(status, -1);
	while (1) {}		/* Make sure we hang here */
}

caddr_t
_sbrk(int incr);

caddr_t
_sbrk(int incr)
{

  extern char _ebss;        // Defined by the linker
  static char* heap_end;
  char* prev_heap_end;

  if (heap_end == 0) {
    heap_end = &_ebss;
  }
  prev_heap_end = heap_end;

  char* stack = (char*)__get_MSP();
  if (heap_end + incr > stack) {
#if 0
    _write(STDERR_FILENO, "Heap and stack collision\n", 25);
#endif
    errno = ENOMEM;

    return (caddr_t)-1;
    // abort ();
  }

  heap_end += incr;
  return (caddr_t)prev_heap_end;
}


/**********************************************************************************************************
 read
 Read a character to a file. `libc' subroutines will use this system routine for
 input from all files, including stdin
 Returns -1 on error or blocks until the number of characters have been read.
 **********************************************************************************************************/

int
_read(int file, char* ptr, int len)
{
  int num = 0;
  circular_buffer* cb_Rx;
  cb_Rx = (circular_buffer*)(stdinout_huart.pRxBuffPtr);
  char tmp;

  switch (file) {
    case STDIN_FILENO:
      /* we could read from USART here */
        num = 0;
        while(num < len)
        {
            if(SUCCESS == cb_pop_front(cb_Rx, &tmp))
            {
                *(ptr + num) = tmp;
                num++;
                if(tmp == EOF) { return num; }
                if(tmp == '\n') { return num; }
            }
        }
      break;

    default:
      errno = EBADF;
      return -1;
  }
  return num;
}


/*********************************************************************************************************
 write
 Write a character to a file. `libc' subroutines will use this system routine
 for output to all files, including stdout
 Returns -1 on error or number of bytes sent
 *********************************************************************************************************/
int
_write(int file, char* ptr, int len)
{
    int num = 0;
    circular_buffer* cb_Tx;

    cb_Tx = (circular_buffer*)(stdinout_huart.pTxBuffPtr);

  switch (file) {
    case STDERR_FILENO: /* stderr */
      /* we could write to USART here */
      //break;  //  write both stderr and stdout to the same uart
    case STDOUT_FILENO: /*stdout*/
      /* we could write to USART here */
        __HAL_UART_DISABLE_IT(&stdinout_huart, UART_IT_TXE);
        while(len)
        {
           if(SUCCESS != cb_push_back(cb_Tx, (ptr + num)))
           {
               __HAL_UART_ENABLE_IT(&stdinout_huart, UART_IT_TXE);
               return num;
           }
           else
           {
               num++;
               len--;
           }
        }
        /* Enable the UART Transmit Data Register Empty Interrupt */
        __HAL_UART_ENABLE_IT(&stdinout_huart, UART_IT_TXE);
      break;

    default:
      errno = EBADF;
      return -1;
  }
  return len;
}

int _close(int file)
{
	return -1;
}


int _fstat(int file, struct stat *st)
{
	st->st_mode = S_IFCHR;
	return 0;
}

int _isatty(int file)
{
	return 1;
}

int _lseek(int file, int ptr, int dir)
{
	return 0;
}

int _open(char *path, int flags, ...)
{
	/* Pretend like we always fail */
	return -1;
}

int _wait(int *status)
{
	errno = ECHILD;
	return -1;
}

int _unlink(char *name)
{
	errno = ENOENT;
	return -1;
}

int _times(struct tms *buf)
{
	return -1;
}

int _stat(char *file, struct stat *st)
{
	st->st_mode = S_IFCHR;
	return 0;
}

int _link(char *old, char *new)
{
	errno = EMLINK;
	return -1;
}

int _fork(void)
{
	errno = EAGAIN;
	return -1;
}

int _execve(char *name, char **argv, char **env)
{
	errno = ENOMEM;
	return -1;
}
